## a) Vorwärtskinematik


In [1]:
import numpy as mp
from math import sin, cos, sqrt, atan2
from transformations import *

In [2]:
# setup of variables
x_r = 2
y_r = 1
r = 0.1
theta = np.radians(30)

In [3]:
TL = trans(np.array((x_r, y_r, r)).transpose())
TL

array([[1. , 0. , 0. , 2. ],
       [0. , 1. , 0. , 1. ],
       [0. , 0. , 1. , 0.1],
       [0. , 0. , 0. , 1. ]])

In [4]:
Rz = rot2trans(rotz(theta))
Rz

array([[ 0.8660254, -0.5      ,  0.       ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [5]:
T_OR = np.matmul(trans(np.array((x_r, y_r,r)).transpose()), rot2trans(rotz(theta)))
T_OR

array([[ 0.8660254, -0.5      ,  0.       ,  2.       ],
       [ 0.5      ,  0.8660254,  0.       ,  1.       ],
       [ 0.       ,  0.       ,  1.       ,  0.1      ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [6]:
l = 0.6
h = 0.2
a = 0 #  simplification, was 0.1

In [7]:
T_R_DB = trans(np.array((l/2-a/2, 0,h)).transpose())
T_R_DB

array([[1. , 0. , 0. , 0.3],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 0.2],
       [0. , 0. , 0. , 1. ]])

In [10]:
alpha = np.radians(40)
b = 0 # simplification! was 0.1

In [11]:
T_DB_D = np.matmul(trans(np.array((0, 0, b/2)).transpose()),
                   np.matmul(rot2trans(rotz(alpha)), rot2trans(rotx(np.radians(90)))))
T_DB_D

array([[ 7.66044443e-01, -3.93593894e-17,  6.42787610e-01,
         0.00000000e+00],
       [ 6.42787610e-01,  4.69066938e-17, -7.66044443e-01,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  6.12323400e-17,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [12]:

l_1 = 0.5
betha_1 = np.radians(30)
l_2 = 0.5
betha_2 = np.radians(-10)

In [13]:
T_D_A1 = np.matmul(trans(np.array((0, 0, a/2)).transpose())
    ,np.matmul(rot2trans(rotz(betha_1)), 
                   trans(np.array((l_1, 0, 0)).transpose())))
T_D_A1

array([[ 0.8660254, -0.5      ,  0.       ,  0.4330127],
       [ 0.5      ,  0.8660254,  0.       ,  0.25     ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [14]:
T_A1_A2 = np.matmul(rot2trans(rotz(betha_2)),
                   trans(np.array((l_2, 0, 0)).transpose())) 
T_A1_A2

array([[ 0.98480775,  0.17364818,  0.        ,  0.49240388],
       [-0.17364818,  0.98480775,  0.        , -0.08682409],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [15]:
p_A2 = np.array((0, 0, 0, 1)).transpose()

In [16]:
p_O = np.matmul(T_OR, 
                np.matmul(T_R_DB, 
                    np.matmul(T_DB_D ,
                        np.matmul(T_D_A1,
                              np.matmul(T_A1_A2, p_A2)))))
p_O

array([2.56860359, 1.99840995, 0.72101007, 1.        ])

In [54]:
#p_O =[2.57228695 1.95630894 0.77101007 1. ]   # Lösung von Prof. Blaich

In [55]:
def calculate_KS_Denavit_Hartenberg(d, theta, a, alpha):
    """
    Calculate the Transformation of one KS to another for the robot arms with Denavit-Hartenberg parameters
    :param d: shift along the old z-axis so that it lies on the new joint axis
    :param theta: rotate around the z-axis so that the old x-axis is in right angle to the new joint axis
    :param a: shift along the old x-axis until the origin is on the new joint axis
    :param alpha: rotate around the new x-axis around alpha so that the z-axis lies on the new joint axis
    :return: transformation
    """
    theta = np.radians(theta)   # my implementation is in radians
    alpha = np.radians(alpha)   # my implementation is in radians
    translation_d = trans((0, 0, d))
    rotate_theta = rot2trans(rotz(theta))
    translation_a = trans((a, 0, 0))
    rotate_alpha = rot2trans(rotx(alpha))
    transformation_ksx_to_ksy = np.matmul(np.matmul(np.matmul(translation_d, rotate_theta), translation_a),
                                          rotate_alpha)
    return transformation_ksx_to_ksy

## Inverse Kinematik

p_R =
 [0.99163013 0.58034659 0.62101007 1.        ]
from Michael Blaich to everyone:    10:57 AM
p_O =
 [2.57228695 1.95630894 0.77101007 1.        ]

In [17]:
p_R = np.matmul(T_R_DB,np.matmul(T_DB_D, np.matmul(T_D_A1, np.matmul(T_A1_A2, p_A2))))
p_R

array([0.99163013, 0.58034659, 0.62101007, 1.        ])

In [29]:
def forward_kinematic(alpha, betha_1, betha_2):
    r = 0.1
    l = 0.6
    h = 0.2
    a = 0 # simplification, was 0.1
    b = 0 # simplification, was 0.1
    l_1 = 0.5
    l_2 = 0.5
    p_A2 = np.array((0, 0, 0, 1)).transpose()
    #print(alpha, np.degrees(alpha))
    #print(betha_1, np.degrees(betha_1))
    #print(betha_2, np.degrees(betha_2))
    
    T_R_DB = trans(np.array((l/2-a/2, 0,h)).transpose())
    T_DB_D = np.matmul(trans(np.array((0, 0, b/2)).transpose()),
                   np.matmul(rot2trans(rotz(alpha)), rot2trans(rotx(np.radians(90)))))
    T_D_A1 = np.matmul(trans(np.array((0, 0, a/2)).transpose()),
                       np.matmul(rot2trans(rotz(betha_1)), 
                           trans(np.array((l_1, 0, 0)).transpose())))
    T_A1_A2 = np.matmul(rot2trans(rotz(betha_2)),
                   trans(np.array((l_2, 0, 0)).transpose())) 
    p_R = np.matmul(T_R_DB,np.matmul(T_DB_D, np.matmul(T_D_A1, np.matmul(T_A1_A2, p_A2))))
    return p_R

In [30]:
forward_kinematic(np.radians(40), np.radians(30), np.radians(-10))
#forward_kinematic(alpha, betha_1, betha_2)

array([0.99163013, 0.58034659, 0.62101007, 1.        ])

In [31]:
def backward_kinematic(p_R):
    r = 0.1
    l = 0.6
    h = 0.2
    a = 0 # simplification, was 0.1
    b = 0 # simplification, was 0.1
    l_1 = 0.5
    l_2 = 0.5
    p_A2 = np.array((0, 0, 0, 1)).transpose()
    
    x_R = p_R[0]
    y_R = p_R[1]
    
    alpha = atan2(y_R, x_R)
    
    T_R_DB = trans(np.array((l/2-a/2, 0,h)).transpose())
    T_DB_R = np.linalg.inv(T_R_DB)
    T_DB_D = np.matmul(trans(np.array((0, 0, b/2)).transpose()),
                   np.matmul(rot2trans(rotz(alpha)), rot2trans(rotx(np.radians(90)))))
    T_D_DB = np.linalg.inv(T_DB_D)
    
    p_D = np.matmul(T_D_DB, np.matmul(T_DB_R, p_R))
    x_D = p_D[0]
    y_D = p_D[1]

    a = sqrt(x_D**2 + y_D**2)
    c = (a**2 - l_1**2 - l_2**2)/2*l_1
    epsilon = -1 # elbow up
    b = epsilon * sqrt(l_2**2 - c**2)
    betha_1 =atan2(y_D, x_D) - atan2(b, (l_1 + c))
    betha_2 = atan2(b, c)

    print("alpha " + str(alpha)+ " " + str(np.degrees(alpha)))
    print("betha_1 " + str(betha_1)+ " " + str(np.degrees(betha_1)))
    print("betha_2 " + str(betha_2)+ " " + str(np.degrees(betha_2)))
    return alpha, betha_1, betha_2

In [32]:
b_alpha, b_betha_1, b_betha_2 = backward_kinematic(p_R)

alpha 0.5294995915107659 30.338091847467997
betha_1 1.1087616649874628 63.52736388967971
betha_2 -1.3338645828243063 -76.42481103781098


In [33]:
forward_kinematic(b_alpha, b_betha_1, b_betha_2)

array([0.91300622, 0.35875883, 0.53597034, 1.        ])