## a) Vorwärtskinematik


In [45]:
import numpy as mp
from math import sin, cos, sqrt, atan2
from transformations import *

In [17]:
# setup of variables
x_r = 2
y_r = 1
r = 0.1
theta = np.radians(30)

In [18]:
TL = trans(np.array((x_r, y_r, r)).transpose())
TL

array([[1. , 0. , 0. , 2. ],
       [0. , 1. , 0. , 1. ],
       [0. , 0. , 1. , 0.1],
       [0. , 0. , 0. , 1. ]])

In [19]:
Rz = rot2trans(rotz(theta))
Rz

array([[ 0.8660254, -0.5      ,  0.       ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [20]:
T_OR = np.matmul(trans(np.array((x_r, y_r,r)).transpose()), rot2trans(rotz(theta)))
T_OR

array([[ 0.8660254, -0.5      ,  0.       ,  2.       ],
       [ 0.5      ,  0.8660254,  0.       ,  1.       ],
       [ 0.       ,  0.       ,  1.       ,  0.1      ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [21]:
l = 0.6
h = 0.2

In [22]:
T_R_DB = trans(np.array((l/2-r, 0,h)).transpose())
T_R_DB

array([[1. , 0. , 0. , 0.2],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 0.2],
       [0. , 0. , 0. , 1. ]])

In [23]:
alpha = np.radians(40)
b = 0.1

In [24]:
T_DB_D = np.matmul(trans(np.array((0, 0, b/2)).transpose()),
                   np.matmul(rot2trans(rotz(alpha)), rot2trans(rotx(np.radians(90)))))
T_DB_D

array([[ 7.66044443e-01, -3.93593894e-17,  6.42787610e-01,
         0.00000000e+00],
       [ 6.42787610e-01,  4.69066938e-17, -7.66044443e-01,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  6.12323400e-17,
         5.00000000e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [25]:
a = 0.1
l_1 = 0.5
betha_1 = np.radians(30)
l_2 = 0.5
betha_2 = np.radians(-10)

In [26]:
T_D_A1 = np.matmul(trans(np.array((0, 0, a/2)).transpose())
    ,np.matmul(rot2trans(rotz(betha_1)), 
                   trans(np.array((l_1, 0, 0)).transpose())))
T_D_A1

array([[ 0.8660254, -0.5      ,  0.       ,  0.4330127],
       [ 0.5      ,  0.8660254,  0.       ,  0.25     ],
       [ 0.       ,  0.       ,  1.       ,  0.05     ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [27]:
T_A1_A2 = np.matmul(rot2trans(rotz(betha_2)),
                   trans(np.array((l_2, 0, 0)).transpose())) 
T_A1_A2

array([[ 0.98480775,  0.17364818,  0.        ,  0.49240388],
       [-0.17364818,  0.98480775,  0.        , -0.08682409],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [28]:
p_A2 = np.array((0, 0, 0, 1)).transpose()

In [29]:
p_O = np.matmul(T_OR, 
                np.matmul(T_R_DB, 
                    np.matmul(T_DB_D ,
                        np.matmul(T_D_A1,
                              np.matmul(T_A1_A2, p_A2)))))
p_O

array([2.52898568, 1.93130894, 0.77101007, 1.        ])

In [15]:
p_O =
[2.57228695 1.95630894 0.77101007 1. ]   # Lösung von Prof. Blaich

SyntaxError: invalid syntax (<ipython-input-15-1e30982be35c>, line 1)

## Inverse Kinematik

In [31]:
p_D = np.matmul(T_D_A1, np.matmul(T_A1_A2, p_A2))
p_D

array([0.90285901, 0.42101007, 0.05      , 1.        ])

In [33]:
x_D = p_D[0]
x_D

0.9028590122851736

In [35]:
z_D = p_D[2] # Seitenansicht!
z_D

0.05

In [40]:
a = sqrt(x_D**2 + z_D**2)
a

0.9042424431890815

In [42]:
c = (a**2 - l_1**2 - l_2**2)/2*l_1
c

0.07941359901613984

In [43]:
epsilon = -1 # elbow up

In [44]:
b = epsilon * sqrt(l_2**2 - c**2)
b

-0.49365319840076366

In [48]:
betha_1 =atan2(z_D, x_D) - atan2(b, (l_1 + c))
betha_1

0.7609699555004501